### ISSUE TITLE
minimit gallery responsive

### ISSUE THREAD

**Issue by Mountaingal** [minimit/minimit-gallery#5]
I'm trying to use Minimit gallery (example9) in a Bootstrap 3 responsive lay-out, but can't seem to find a way to make the gallery itself responsive. Not sure if that's even possible, but any help or suggestions would be greatly appreciated (if it can't be done, then please just say tell me, so I can stop pulling my hair out, and try to find a viable alternative).
Thanks!

**Comment by minimit** [comment]
Yes i don't think it's possible without complicated code that recalculate the items position when you resize, sorry better find an alternative
